//
//  Mediaitem.swift
//  HistoriaApp
//
//  Created by David on 14.08.17.
//  Copyright © 2017 David. All rights reserved.
//

import Foundation

public class Mediaitem {
    
    // TODO: a simple id generated by the db
    // var id: UInt64 = 0
    
    // A url (wordpress guid) via which the mediaitem may be identified
    // NOTE: This is unique on the backend, but may exist multiple times
    //       in the app's db. (Though only once for each page
    // TODO: Ensure that the combination of page and guid is unique
    var guid: String = ""
    
    // the page this media item belongs to
    var page: Page?
    
}
